name: Deploy to Contabo VM

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: |
            backend/package-lock.json
            frontend/package-lock.json

      - name: Install Backend Dependencies
        run: |
          cd backend
          npm ci --production

      - name: Install Frontend Dependencies
        run: |
          cd frontend
          npm ci

      - name: Build Frontend
        run: |
          cd frontend
          npm run build
        env:
          REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
          CI: false

      - name: Deploy to Contabo VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # Navigate to app directory
            cd /var/www/parc360

            # Pull latest code
            git pull origin main

            # Install backend dependencies
            cd backend
            npm ci --production

            # Install frontend dependencies and build
            cd ../frontend
            npm ci
            npm run build

            # Restart backend with PM2
            cd ..
            pm2 restart parc360-backend || pm2 start backend/server.js --name parc360-backend

            # Copy frontend build to Nginx
            sudo cp -r frontend/build/* /var/www/parc360/frontend/build/

            # Reload Nginx
            sudo systemctl reload nginx

            echo "Deployment completed successfully!"

      - name: Notify Deployment Success
        if: success()
        run: echo "✅ Deployment to Contabo VM completed successfully!"

      - name: Notify Deployment Failure
        if: failure()
        run: echo "❌ Deployment to Contabo VM failed!"
